/*CRIANDO BANCO COMERCIO */

CREATE DATABASE COMERCIO
GO

USE COMERCIO
GO

/*MODELANDO A TABELA CLIENTE */

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	CPF INT UNIQUE,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
	EMAIL VARCHAR(50) UNIQUE
	)
	GO
/*MODELANDO A TABELA ENDERECO */

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY(1,1),
	TIPO CHAR(3) CHECK(TIPO IN('RES','CEL','COM')),
	NUMERO VARCHAR(11),
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
	)
GO

/*MODELANDO A TABELA TELEFONE */

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(1,1),
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
)
GO

/*MODELANDO A CHAVE ESTRANGEIRA - ESTÁ ACIMA */

/*INSERINDO DADOS NA TABELA CLIENTE */

INSERT INTO CLIENTE VALUES('RICARDO SOARES','048139418','M','risoares@yahoo.com.br')
INSERT INTO CLIENTE VALUES('GIOVANA SOARES','168139418','M','gisoares@yahoo.com.br')
INSERT INTO CLIENTE VALUES('MARIA SOARES','234139418','F',NULL)
INSERT INTO CLIENTE VALUES('DANIEL SOARES','139139456','M','daniels@yahoo.com.br')
GO

SELECT * FROM CLIENTE
GO


/*INSERINDO DADOS NA TABELA ENDERECO */

INSERT INTO ENDERECO VALUES('RUA ANTONIO AMBUBA, 80','JD MUNHOZ','SÃO PAULO','SP',2)
INSERT INTO ENDERECO VALUES('RUA ANTONIO AMBUBA, 80','JD MUNHOZ','RIO JANEIRO','RJ',3)
INSERT INTO ENDERECO VALUES('RUA ANTONIO AMBUBA, 80','JD MUNHOZ','BELO HORIZONTE','MG',4)
INSERT INTO ENDERECO VALUES('RUA ANTONIO AMBUBA, 80','JD MUNHOZ','SÃO PAULO','SP',5)
GO

SELECT * FROM ENDERECO
GO

/*INSERINDO DADOS NA TABELA TELEFONE */

INSERT INTO TELEFONE VALUES('CEL','997149142','2')
INSERT INTO TELEFONE VALUES('CEL','929149142','2')
INSERT INTO TELEFONE VALUES('CEL','997168142','3')
INSERT INTO TELEFONE VALUES('CEL','997149142','3')
INSERT INTO TELEFONE VALUES('CEL','997145142','4')
INSERT INTO TELEFONE VALUES('CEL','997149142','5')
INSERT INTO TELEFONE VALUES('CEL','987149138','5')
GO

SELECT * FROM TELEFONE
GO

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO='M'
GO

SELECT NOW()
GO

UPDATE CLIENTE
SET EMAIL='maria@gmail.com'
WHERE IDCLIENTE = 4
GO

SELECT * FROM CLIENTE
GO

SELECT NOME, SEXO, BAIRRO, CIDADE, GETDATE() AS DATA
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE=ID_CLIENTE
GO

SELECT NOME,NUMERO, GETDATE() AS DATA
FROM CLIENTE, TELEFONE
WHERE IDCLIENTE=ID_CLIENTE
GO

SELECT NOME, SEXO, NUMERO, GETDATE() AS DATA
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'M'
GO

SELECT NOME, TIPO, NUMERO, EMAIL
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'
GO

SELECT * FROM ENDERECO
GO

INSERT INTO CLIENTE VALUES('DALMO FIERZ','135467456','M',NULL)
GO

INSERT INTO TELEFONE VALUES('CEL',NULL,'6')
GO

INSERT INTO ENDERECO VALUES('RUA GASPAR COQUEIRO, 249','JARDIM PIRACUAMA','PORTO ALEGRE','RS',6)
GO

SELECT	CLIENTE.NOME,
		ENDERECO.RUA AS ENDERECO, 
		ISNULL(TELEFONE.NUMERO, 'SEM CELULAR') AS CELULAR
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE ESTADO = 'RS' OR SEXO = 'M'
GO

/*CRIANDO VIEWS(VISÕES) - RELATORIOS PRÉ PRONTOS */

CREATE VIEW RELATORIO AS
SELECT	CLIENTE.NOME,
		ENDERECO.RUA AS ENDERECO, 
		ISNULL(TELEFONE.NUMERO, 'SEM CELULAR') AS CELULAR
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE ESTADO = 'RS' OR SEXO = 'M'
GO

SELECT * FROM RELATORIO
WHERE CELULAR = 'SEM CELULAR'
GO

USE COMERCIO
GO

SELECT 10+10 AS 'CONTA'
GO

CREATE PROCEDURE CONTAR
AS
BEGIN
SELECT 20 + 20 AS 'SOMA'
END
GO

EXEC CONTA
GO

/*CRIANDO PROCEDURES COMPARAMETROS */

CREATE PROCEDURE CONTAR(NUM1 AS INT, NUM2 AS INT)
AS BEGIN
SELECT NUM1 + NUM2
END
GO

EXEC CONTAR

/*VERICANDO A ESTRUTURA DE PROCEDURES ATRAVES DO COMANDO SP_HELPTEXT */

EXEC SP_HELPTEXT CONTAR

/*ALTERANDO A ESTRUTURA DE PROCEDURES */

CREATE PROCEDURE CONTARA
(5 AS INT,'Y' AS INT)
AS
BEGIN
	SELECT 5 + 'Y'
END